name: Quote of the Day

on:
  schedule:
    - cron: "0 0 * * *" # every day at 06:00 UTC
  workflow_dispatch: {} # Allows manual triggering

permissions:
  contents: write

jobs:
  fetch-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick random quote
        run: |
          node -e '
            const fs = require("fs");
            const data = JSON.parse(fs.readFileSync("quotes/all.json", "utf8"));
            const authors = Object.keys(data);
            const author = authors[Math.floor(Math.random() * authors.length)];
            const quotes = data[author];
            const quote = quotes[Math.floor(Math.random() * quotes.length)];
            if (quote) {
              const output = { author, quote };
              fs.writeFileSync("quotes/daily.json", JSON.stringify(output, null, 2));
            } else {
              console.error("No quote found. Skipping.");
            }
          '

      - name: Commit and push if changed
        run: |
          if git diff --quiet quotes/daily.json; then
            echo "No changes to commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add quotes/daily.js
            git commit -m "Update quote of the day"
            git push
          fi
