name: Update Stats JSON

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: {} # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Reddit
        id: reddit
        run: |
          # Fetch the raw JSON response from Discord
          RESPONSE=$(curl -s "https://www.reddit.com/r/HellDads/")
          echo "Raw Discord response:"
          echo "$RESPONSE"

      - name: Fetch Discord Data
        id: discord
        run: |
          # Fetch the raw JSON response from Discord
          RESPONSE=$(curl -s "https://discord.com/api/invites/7rbdFMmGCz?with_counts=true&with_expiration=true")
          echo "Raw Discord response:"
          echo "$RESPONSE"
          # Parse the approximate_member_count from the response
          MEMBERS=$(echo "$RESPONSE" | jq '.approximate_member_count')
          echo "members=$MEMBERS" >> $GITHUB_OUTPUT

      - name: Update stats.json file
        run: |
          mkdir -p data
          echo '{' > stats.json
          echo '  "discord": { "approximate_member_count": '"${{ steps.discord.outputs.members }}"' },' >> stats.json
          echo '  "lastUpdated": "'"$(date --utc +'%Y-%m-%dT%H:%M:%SZ')"'"' >> stats.json
          echo '}' >> stats.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Discord stats"
            git push
          fi
